Traceback (most recent call last):
  File "/home/zmaw/u290401/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/sw/buster-x64/anaconda3-2022.05/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from siphon import catalog

cat = catalog.TDSCatalog('https://icdc.cen.uni-hamburg.de/thredds/catalog.xml')
print(list(cat.catalog_refs))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msiphon[39;00m [38;5;28;01mimport[39;00m catalog
[1;32m      3[0m cat [38;5;241m=[39m catalog[38;5;241m.[39mTDSCatalog([38;5;124m'[39m[38;5;124mhttps://icdc.cen.uni-hamburg.de/thredds/catalog.xml[39m[38;5;124m'[39m)
[1;32m      4[0m [38;5;28mprint[39m([38;5;28mlist[39m(cat[38;5;241m.[39mcatalog_refs))

[0;31mModuleNotFoundError[0m: No module named 'siphon'
ModuleNotFoundError: No module named 'siphon'

